# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser_functionality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=10)),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser_functionality.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tel_number', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='singlesubscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_functionality.User'),
        ),
    ]
