# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser_functionality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
