# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('rate', models.FloatField(max_length=64)),
                ('refresh', models.DateTimeField()),
                ('zone', models.CharField(max_length=3)),
            ],
        ),
    ]
