# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('time', models.DateTimeField()),
                ('zone', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='refresh',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='zone',
        ),
        migrations.AddField(
            model_name='rate',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
        ),
    ]
